[global]
server_name = "anycompany.corp"
database_backend = "rocksdb"
database_path = "/var/lib/matrix-conduit/database"
port = 6167
max_request_size = 20_000_000
allow_registration = true
allow_federation = true
trusted_servers = ["matrix.org"]
address = "0.0.0.0"
